#!/bin/bash
# 
#Testing the properties of strings
#
# zero or nonzero length  (2 equivalent ways)


VAR="$1"
#
if [ "$VAR" ]
then
echo has text
else
echo zero length
fi
#
if [ -z "$VAR" ]
then
echo zero length
else
echo has text
fi
#
#beware when testing equalities, do you want strings to be treated 
#as strings or numbers??
#
VAR1=" 05 "
VAR2="5"
printf "%s" "do they -eq as equal? "
if [ "$VAR1" -eq "$VAR2" ]
then
echo YES
else
echo NO
fi
printf "%s" "do they = as equal? "
if [ "$VAR1" == "$VAR2" ]
then
echo YES
else
echo NO
fi

#
# testing for pattern matches
#
MYFILENAME="testfile.jpg"
if [[ "${MYFILENAME}" == *.jpg ]]
then
printf "file %s found \n" "$MYFILENAME"
fi
